/*
 * =====================================================================
 *  IshizukiTech LLC — Survey App (Streaming Bridge)
 *  ---------------------------------------------------------------------
 *  File: ChatStreamEvent.kt
 *  Author: Shu Ishizuki
 *  License: MIT License
 *  © 2026 IshizukiTech LLC. All rights reserved.
 * =====================================================================
 */

@file:Suppress("unused")

package com.negi.surveys.chat

/**
 * Streaming events emitted by the model layer.
 *
 * Design:
 * - All events are tagged with a sessionId so the ViewModel can safely
 *   ignore stale/overlapping streams.
 *
 * Note:
 * - sessionId is a monotonically increasing Long generated by [ChatStreamBridge].
 */
sealed interface ChatStreamEvent {

    /** Stream session started. */
    data class Begin(val sessionId: Long) : ChatStreamEvent

    /** Incremental token/text delta. */
    data class Delta(val sessionId: Long, val text: String) : ChatStreamEvent

    /** Stream session completed normally. */
    data class End(val sessionId: Long) : ChatStreamEvent

    /** Stream session failed. */
    data class Error(val sessionId: Long, val reason: String) : ChatStreamEvent
}
