/*
 * =====================================================================
 *  IshizukiTech LLC — Survey App (Streaming Bridge)
 *  ---------------------------------------------------------------------
 *  File: ChatStreamEvent.kt
 *  Author: Shu Ishizuki
 *  License: MIT License
 *  © 2026 IshizukiTech LLC. All rights reserved.
 * =====================================================================
 */

@file:Suppress("unused")

package com.negi.surveys.chat

import androidx.compose.runtime.Immutable

/**
 * Streaming events emitted by the model layer.
 *
 * Design:
 * - Every event carries a [sessionId] so the ViewModel can safely ignore stale/overlapping streams.
 *
 * Session:
 * - [sessionId] is a monotonically increasing value generated by ChatStreamBridge.
 *
 * Compose note:
 * - [Immutable] is a Compose hint (optimization metadata), not an enforcement mechanism.
 *   Keep payload types genuinely immutable by convention.
 *
 * Payload guidance:
 * - [Delta.text] should be a small incremental chunk (avoid huge blobs).
 * - [Error] must not carry PII. Prefer stable, short tokens/codes over raw exception messages.
 */
@Immutable
sealed interface ChatStreamEvent {

    /**
     * Stable tokens/codes shared across Bridge/VM/UI.
     */
    object Codes {
        const val CANCELLED: String = "cancelled"
        const val REPLACED: String = "replaced"
        const val TIMEOUT: String = "timeout"
        const val ERROR: String = "error"
    }

    /** Stream session started. */
    @Immutable
    data class Begin(val sessionId: Long) : ChatStreamEvent

    /**
     * Incremental token/text delta.
     *
     * Notes:
     * - [text] should be small and append-only.
     * - Avoid emitting empty strings unless you explicitly want a "heartbeat".
     */
    @Immutable
    data class Delta(
        val sessionId: Long,
        val text: String
    ) : ChatStreamEvent

    /** Stream session completed normally. */
    @Immutable
    data class End(val sessionId: Long) : ChatStreamEvent

    /**
     * Stream session failed.
     *
     * @param token Short, metadata-only token (e.g., "TimeoutCancellationException", "io_error").
     * @param code Optional stable code for programmatic handling (e.g., "timeout", "cancelled", "replaced").
     */
    @Immutable
    data class Error(
        val sessionId: Long,
        val token: String,
        val code: String? = null
    ) : ChatStreamEvent
}