/*
 * =====================================================================
 *  IshizukiTech LLC — Survey App (Streaming Bridge)
 *  ---------------------------------------------------------------------
 *  File: ChatStreamEvent.kt
 *  Author: Shu Ishizuki
 *  License: MIT License
 *  © 2026 IshizukiTech LLC. All rights reserved.
 * =====================================================================
 */

@file:Suppress("unused")

package com.negi.surveys.chat

import androidx.compose.runtime.Immutable

/**
 * Streaming events emitted by the model layer.
 *
 * Design:
 * - All events are tagged with a sessionId so the ViewModel can safely
 *   ignore stale/overlapping streams.
 *
 * Session:
 * - sessionId is a monotonically increasing Long generated by [ChatStreamBridge].
 *
 * Payload guidance (recommended):
 * - [Delta.text] should be a small incremental chunk (avoid huge blobs).
 * - [Error.reason] should be short and metadata-only (no PII).
 */
@Immutable
sealed interface ChatStreamEvent {

    /** Stream session started. */
    @Immutable
    data class Begin(val sessionId: Long) : ChatStreamEvent

    /** Incremental token/text delta. */
    @Immutable
    data class Delta(val sessionId: Long, val text: String) : ChatStreamEvent

    /** Stream session completed normally. */
    @Immutable
    data class End(val sessionId: Long) : ChatStreamEvent

    /** Stream session failed. */
    @Immutable
    data class Error(val sessionId: Long, val reason: String) : ChatStreamEvent
}